#cloud-config

coreos:
  units:
    - name: docker-tcp.socket
      command: start
      enable: yes
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        BindIPv6Only=both
        Service=docker.service

        [Install]
        WantedBy=sockets.target
    - name: enable-docker-tcp.service
      command: start
      content: |
        [Unit]
        Description=Enable the Docker Socket for the API

        [Service]
        Type=oneshot
        ExecStart=/usr/bin/systemctl enable docker-tcp.socket
   users:
     - name: core
       ssh-authorized-keys:
         - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvaN0QcaNJpR941f+/+lVEeTXfTpFGd5Ehdy+58QalvJjX+kisolVG6YxuWJs3w2fnLCEdTAUE0V6Oglxn7zL2XrBGha54DJ4T7LQuDudxc4mF9xeq3vV4JDAIlxfzcZQ7PsXjbdsLK7mxlbcHaAcb2FSQy+vEXMQCGADK5w/2QYMrzP8I70H7rbDsjl8BkiVLkWoV6+TVSgbaCkzieKyAsoWGL+lK2db+AdHUX+2CaZ17fChnPVDa+IkFMb2erCKgtoQrJZmVhF3XqAL1pJAfK7EuVAxVxSYnBBOIuV5lEbuzFNoU2nMeFVy9nZaW4MSk9CPV4spRDfrGhSBIjO5h chris@macalone

     - groups:
         - sudo
         - docker
