#cloud-config

hostname: etcd1

coreos:
  etcd:
    addr: 192.168.122.10:2375
    peer-addr: 192.168.1.10:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: static.network
      content: |
        [Match]
        Name=eth0

        [Network]
        Address=192.168.122.10/24
        Gateway=192.168.122.1
        DNS=8.8.8.4
        DNS=8.8.8.8
users:
  - name: core
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCvaN0QcaNJpR941f+/+lVEeTXfTpFGd5Ehdy+58QalvJjX+kisolVG6YxuWJs3w2fnLCEdTAUE0V6Oglxn7zL2XrBGha54DJ4T7LQuDudxc4mF9xeq3vV4JDAIlxfzcZQ7PsXjbdsLK7mxlbcHaAcb2FSQy+vEXMQCGADK5w/2QYMrzP8I70H7rbDsjl8BkiVLkWoV6+TVSgbaCkzieKyAsoWGL+lK2db+AdHUX+2CaZ17fChnPVDa+IkFMb2erCKgtoQrJZmVhF3XqAL1pJAfK7EuVAxVxSYnBBOIuV5lEbuzFNoU2nMeFVy9nZaW4MSk9CPV4spRDfrGhSBIjO5h chris@macalone

  - groups:
      - sudo
      - docker
